language: python
sudo: false
python:
    - "3.5"
    - "3.6"
install:
    - pip install -U pip wheel
    - pip install -r requirements_dev.txt
script:
    - flake8 sepadd tests
    - isort -rc -c sepadd tests
    - pytest tests/
cache:
    directories:
        - $HOME/.cache/pip
